"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
# Disable arrow keys for navigation.
prepend_keymap = [
    { on = "<Left>",  run = "noop" },
    { on = "<Down>", run = "noop" },
    { on = "<Up>",   run = "noop" },
    { on = "<Right>", run = "noop" },
]

