"$schema" = "https://starship.rs/config-schema.json"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[username]
show_always = true

[hostname]
ssh_symbol = "ssh "

[directory]
truncation_length = 0

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = "git "
truncation_symbol = "..."

[package]
symbol = "pkg "

[sudo]
symbol = "sudo "

[c]
symbol = "c "

[cpp]
symbol = "c++ "

[cmake]
symbol = "cmake "

[java]
symbol = "java "

[lua]
symbol = "lua "

[python]
symbol = "py "

[rust]
symbol = "rs "

[zig]
symbol = "zig "
